### ISSUE TITLE
unable to search for pods by label containing dash

### ISSUE THREAD

**Issue by iamryanchia** [KusionStack/karpor#576]
### What would you like to be added?

The pod labels can contain dashes, as described in [syntax-and-character-set](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set). However, searching for pods with label containing a dash will result in an error. 

<img width="1383" alt="2024-08-06 17 58 29" src="https://github.com/user-attachments/assets/a219047e-0dd4-49e6-9e7c-1625a51a8c7d">

### Why is this needed?

unable to search for pods by valid label

**Comment by elliotxx** [comment]
@iamryanchia Got it, let's take a look

**Comment by gshilei** [comment]
Hi, I want to try to solve this problem, but I found that the above query writing method may not be correct. The value in string format must be enclosed in single or double quotation marks, otherwise it will be parsed as a column name by SQL parser. If the above label value is enclosed in single or double quotation marks, this problem will be solved.

The test results as below:
* single quotation
![image](https://github.com/user-attachments/assets/e3b87817-8ee6-4475-95d7-cf14dbd2d61d)

* double quotation
![image](https://github.com/user-attachments/assets/d9d25101-f148-4ef1-9444-a52e9e477cba)

**Comment by ruquanzhao** [comment]
@gshilei 
Thank you for trying to reproduce this issue! It doesn't seem to be a bug, so let's close this issue.
